---
name: publish
on:
  push:
    branches-ignore:
      - '*'
    tags:
      - 'v[0-9]*'
  workflow_dispatch:
    inputs:
      version:
        description: "Version to be published (e.g., v1.43.0, v1.43.0-1)"
        required: true
        type: string
        default: "latest"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get image tags
        id: image_tags
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            # For workflow_dispatch, use only the version provided
            VERSION=${{ github.event.inputs.version }}
            RELEASE=${{ github.event.inputs.version }}
            echo "IMAGE_TAGS=${VERSION}" >> $GITHUB_OUTPUT
          else
            # For tag events, use semantic versioning tags
            # GITHUB_REF will be of the form "refs/tags/v0.1.2" or "refs/tags/v0.1.2-1"
            # To determine VERSION, strip off the leading "refs/tags/"
            VERSION=${GITHUB_REF#refs/tags/}
            echo "IMAGE_TAGS=latest ${VERSION%.*} ${VERSION}" >> $GITHUB_OUTPUT
          fi

      - name: Buildah Action
        id: buildah-build
        if: steps.image_tags.outputs.IMAGE_TAGS
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ vars.IMAGE_NAME }}
          tags: ${{ steps.image_tags.outputs.IMAGE_TAGS }}
          containerfiles: Containerfile

      - name: Push image to registry
        id: push-to-registry
        if: steps.image_tags.outputs.IMAGE_TAGS
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.buildah-build.outputs.image }}
          tags: ${{ steps.buildah-build.outputs.tags }}
          registry: ${{ vars.IMAGE_REGISTRY }}/${{ vars.IMAGE_REPOSITORY }}
          username: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
